apiVersion: v1
kind: Service
metadata:
  name: vllm-service
spec:
  selector:
    app: gemma-server
  ports:
    - name: http-vllm
      protocol: TCP
      port: 8000
      targetPort: 8000
  sessionAffinity: None
  type: LoadBalancer

# ClusterIP (Internal)
# apiVersion: v1
# kind: Service
# metadata:
#   name: llm-service
# spec:
#   selector:
#     app: gemma-server
#   type: ClusterIP
#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000