apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vllm
    spec:
      containers:
      - name: vllm
        image: vllm/vllm-openai:latest
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve facebook/opt-125m"
        ]
        ports:
          - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
          - name: model-cache
            mountPath: /root/.cache/huggingface
      nodeSelector:
        gpu.nvidia.com/class: L40S # New selector for specific GPU class
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: vllm-models