apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-rwo  # GKE-specific storage class for better performance
  resources:
    requests:
      storage: 60Gi
  volumeMode: Filesystem
