# prometheus-k8s.yaml
global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: vllm-k8s
    static_configs:
      - targets:
          - 'vllm-server:8000'  # Kubernetes service name
    metrics_path: '/metrics'
    scrape_interval: 5s 