[project]
name = "vllm-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=0.34.4",
    "openai>=1.90.0",
    "ray[llm,serve]>=2.48.0",
    "vllm>=0.10.0",
]
