apiVersion: v1
kind: Service
metadata:
  name: vllm-server
spec:
  selector:
    app.kubernetes.io/name: vllm
  ports:
    - name: http-vllm
      protocol: TCP
      port: 8000
      targetPort: 8000
  sessionAffinity: None
  type: LoadBalancer