apiVersion: v1
kind: Service
metadata:
  name: stable-diffusion-service
  labels:
    type: external
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: stable-diffusion